#!/bin/sh

SERVICES_FILE="$HOME/.gservices.sh"
BSPWM_SERVICES_FILE="$HOME/.config/bspwm/services.sh"

if [ ! -f "$SERVICES_FILE" ]; then
    exit 1
fi

if [ ! -x "$SERVICES_FILE" ]; then
    chmod +x "$SERVICES_FILE"
fi

if [ ! -f "$BSPWM_SERVICES_FILE" ]; then
    exit 1
fi

if [ ! -x "$BSPWM_SERVICES_FILE" ]; then
    chmod +x "$BSPWM_SERVICES_FILE"
fi

bspc monitor -d 1 2 3 4 5

bspc config border_width          2
bspc config window_gap            12
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc rule -a Gimp state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a feh state=floating
bspc rule -a Qemu-system-i386 state=floating

bspc config normal_border_color  "#514D59"
bspc config focused_border_color "#E5C07B"

xsetroot -cursor_name left_ptr &

setxkbmap br
feh --bg-scale "$HOME/Pictures/Wallpapers/viozene-circuits-dark.png"

"$SERVICES_FILE" &
"$BSPWM_SERVICES_FILE" &
