#!/bin/sh

bspc monitor -d 1 2 3 4 5

bspc config border_width          2
bspc config window_gap            12
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc rule -a Gimp state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a feh state=floating
bspc rule -a Qemu-system-i386 state=floating

bspc config normal_border_color  "#3c3836"
bspc config focused_border_color "#458588"

sxhkd &
feh --bg-scale $HOME/.wallpaper &
setxkbmap br
mpd --no-daemon &
dunst &
pipewire &
pipewire-pulse &
wireplumber &
polybar &
picom &

