#!/bin/sh
# appearance/apply.sh - render every appearance config from the appearance
# module (settings.conf + dark.conf / light.conf) and apply it to the session.
#
# Usage:
#   apply.sh [dark|light]   render and apply a specific theme
#   apply.sh                use the cached theme (or the default)
#
# Generated files:
#   ~/.Xresources                      terminal palette, fonts, cursor
#   ~/.config/polybar/colors.ini       bar colors
#   ~/.config/gtk-3.0/settings.ini     cursor + dark preference
#   ~/.config/gtk-4.0/settings.ini     cursor + dark preference
#   ~/.icons/default/index.theme       cursor theme fallback
#   ~/.wallpaper                       wallpaper symlink
#   ~/.cache/solarized                 current theme

set -eu

APP_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/appearance"
CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}"
STATE_FILE="$CACHE_DIR/solarized"

if [ $# -ge 1 ]; then
	theme="$1"
elif [ -f "$STATE_FILE" ]; then
	theme="$(cat "$STATE_FILE")"
else
	theme=dark
fi

case "$theme" in
	dark|light) ;;
	*) printf 'Unknown theme: %s (expected dark|light)\n' "$theme" >&2; exit 1 ;;
esac

# shellcheck disable=SC1090
. "$APP_DIR/settings.conf"
# shellcheck disable=SC1090
. "$APP_DIR/$theme.conf"

# Remember the active theme so vim (and others) stay in sync.
mkdir -p "$CACHE_DIR"
printf '%s\n' "$theme" > "$STATE_FILE"

# --- ~/.Xresources (terminal palette, fonts, cursor) ---
cat > "$HOME/.Xresources" <<EOF
! Generated by ~/.config/appearance/apply.sh -- edit the appearance module instead.
Xcursor.theme: ${CURSOR_THEME}
Xcursor.size: ${CURSOR_SIZE}

URxvt*font: xft:${TERM_FONT}:size=${TERM_FONT_SIZE},xft:${ICON_FONT}:size=${ICON_FONT_SIZE}
URxvt*scrollBar: false

! URxvt palette
URxvt*background: ${PALETTE_BACKGROUND}
URxvt*foreground: ${PALETTE_FOREGROUND}

URxvt*color0:  ${PALETTE_0}
URxvt*color1:  ${PALETTE_1}
URxvt*color2:  ${PALETTE_2}
URxvt*color3:  ${PALETTE_3}
URxvt*color4:  ${PALETTE_4}
URxvt*color5:  ${PALETTE_5}
URxvt*color6:  ${PALETTE_6}
URxvt*color7:  ${PALETTE_7}

URxvt*color8:  ${PALETTE_8}
URxvt*color9:  ${PALETTE_9}
URxvt*color10: ${PALETTE_10}
URxvt*color11: ${PALETTE_11}
URxvt*color12: ${PALETTE_12}
URxvt*color13: ${PALETTE_13}
URxvt*color14: ${PALETTE_14}
URxvt*color15: ${PALETTE_15}
EOF

# --- polybar colors ---
mkdir -p "$HOME/.config/polybar"
cat > "$HOME/.config/polybar/colors.ini" <<EOF
[colors]
background = ${PALETTE_BACKGROUND}
foreground = ${PALETTE_FOREGROUND}
primary   = ${POLYBAR_PRIMARY}
secondary = ${POLYBAR_SECONDARY}
alert     = ${POLYBAR_ALERT}
muted     = ${POLYBAR_MUTED}
EOF

# --- gtk settings (cursor + dark preference) ---
for f in "$HOME/.config/gtk-3.0/settings.ini" "$HOME/.config/gtk-4.0/settings.ini"; do
	mkdir -p "$(dirname "$f")"
	cat > "$f" <<EOF
[Settings]
gtk-cursor-theme-name=${CURSOR_THEME}
gtk-cursor-theme-size=${CURSOR_SIZE}
gtk-application-prefer-dark-theme=${GTK_DARK}
EOF
done

# --- user cursor theme fallback ---
mkdir -p "$HOME/.icons/default"
cat > "$HOME/.icons/default/index.theme" <<EOF
[Icon Theme]
Inherits=${CURSOR_THEME}
EOF

# --- wallpaper ---
WALL_DIR="$HOME/Pictures/wallpapers"
if [ "$theme" = dark ]; then
	WALL="$WALL_DIR/$WALLPAPER_DARK"
else
	WALL="$WALL_DIR/$WALLPAPER_LIGHT"
fi
if [ -f "$WALL" ]; then
	ln -sf "$WALL" "$HOME/.wallpaper"
fi

# --- live session updates ---
if [ -n "${DISPLAY:-}" ]; then
	if command -v xrdb >/dev/null 2>&1; then
		xrdb "$HOME/.Xresources" || true
	fi
	if command -v bspc >/dev/null 2>&1; then
		bspc config normal_border_color  "$BORDER_NORMAL"  2>/dev/null || true
		bspc config focused_border_color "$BORDER_FOCUSED" 2>/dev/null || true
	fi
	if command -v feh >/dev/null 2>&1 && [ -f "$HOME/.wallpaper" ]; then
		feh --bg-scale "$HOME/.wallpaper" >/dev/null 2>&1 || true
	fi
	if command -v polybar-msg >/dev/null 2>&1; then
		polybar-msg cmd restart >/dev/null 2>&1 || true
	fi
	if command -v gsettings >/dev/null 2>&1; then
		if [ "$theme" = dark ]; then
			gsettings set org.gnome.desktop.interface color-scheme prefer-dark 2>/dev/null || true
		else
			gsettings set org.gnome.desktop.interface color-scheme default 2>/dev/null || true
		fi
	fi
fi