backend = "glx";
vsync = true;
detect-client-opacity = true;
use-damage = true;
unredir-if-possible = true;

# Bordas arredondadas
rounded-corners = true
corner-radius = 12

# Sombras
shadow = true;
shadow-radius = 12;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.5;

# Fading
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;

# Blur
blur-method = "dual_kawase";
blur-strength = 3;
blur-background = true;
blur-background-frame = true;

# Regras de opacidade e comportamento de janelas
rules = (
  { match = "class_g = 'st-256color'"; opacity = 0.80; },
  { match = "class_g = 'Sober'"; unredir-if-possible = false; },
);

# ANIMAÇÕES
animations = (
  # ABRIR
  {
    triggers = ["open"];
    scale-x = {
      curve = "cubic-bezier(0.68, -0.55, 0.265, 1.55)";
      duration = 0.5;
      start = 0.0;
      end = 1.0;
    };
    scale-y = "scale-x";
    offset-x = {
      curve = "cubic-bezier(0.68, -0.55, 0.265, 1.55)";
      duration = 0.5;
      start = "window-width / 2";
      end = 0;
    };
    offset-y = {
      curve = "cubic-bezier(0.68, -0.55, 0.265, 1.55)";
      duration = 0.5;
      start = "window-height / 2";
      end = 0;
    };
    opacity = {
      curve = "cubic-bezier(0.25, 0.46, 0.45, 0.94)";
      duration = 0.4;
      start = 0;
      end = 1;
    };
  },

  # FECHAR
  {
    triggers = ["close"];
    scale-x = {
      curve = "cubic-bezier(0.6, 0, 0.8, 0.2)";
      duration = 0.3;
      start = 1.0;
      end = 0.0;
    };
    scale-y = "scale-x";
    offset-x = {
      curve = "cubic-bezier(0.6, 0, 0.8, 0.2)";
      duration = 0.3;
      start = 0;
      end = "window-width / 2";
    };
    offset-y = {
      curve = "cubic-bezier(0.6, 0, 0.8, 0.2)";
      duration = 0.3;
      start = 0;
      end = "window-height / 2";
    };
    opacity = {
      curve = "cubic-bezier(0.25, 0.46, 0.45, 0.94)";
      duration = 0.3;
      start = 1;
      end = 0;
    };
  },

  # MINIMIZAR
  {
    triggers = ["hide"];
    offset-y = {
      curve = "cubic-bezier(0.25, 0.46, 0.45, 0.94)";
      duration = 0.25;
      start = 0;
      end = "window-height + 50";
    };
    opacity = {
      duration = 0.2;
      start = 1;
      end = 0;
    };
  },

  # RESTAURAR
  {
    triggers = ["show"];
    offset-y = {
      curve = "cubic-bezier(0.25, 0.46, 0.45, 0.94)";
      duration = 0.25;
      start = "window-height + 50";
      end = 0;
    };
    opacity = {
      duration = 0.2;
      start = 0;
      end = 1;
    };
  },

  # GEOMETRY
  {
    triggers = ["geometry"];
    preset = "geometry-change";
    duration = 0.25;
  }
);
