# Picom configuration

backend = "glx";

shadow = true;

blur = {
    method = "gaussian";
    size = 10;
    deviation = 5.0;
};

rules = (
    { match = "focused && name != 'alacritty'"; opacity = 1.0; },
    { match = "!focused || name = 'alacritty'"; opacity = 0.85; },
    { match = "class_g = 'Polybar'"; shadow = false; opacity = 1.0; }
)

animations = ({
            triggers = ["close", "hide"];
            preset = "disappear";
            scale = 0.6;
        }, {
            triggers = ["open", "show"];
            preset = "appear";
            scale = 0.6;
        })
