# Picom configuration

rules = (
    { match = "focused && name != 'st'"; opacity = 1.0; },
    { match = "!focused || name = 'st'"; opacity = 0.85; }
)

blur = {
    method = "gaussian";
    size = 10;
    deviation = 5.0;
};

animations = ({
            triggers = ["close", "hide"];
            preset = "disappear";
            scale = 0.6;
        }, {
            triggers = ["open", "show"];
            preset = "appear";
            scale = 0.6;
        })
